# Generated by Django 4.1.4 on 2023-04-16 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(11)],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "no_of_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxLengthValidator(6)]
                    ),
                ),
                ("booking_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(5)],
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxLengthValidator(5)]
                    ),
                ),
            ],
        ),
    ]
