# Generated by Django 4.1.4 on 2023-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.PositiveIntegerField(
                max_length=11, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.PositiveIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.PositiveIntegerField(
                max_length=5, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
