# Generated by Django 4.1.4 on 2023-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_id_alter_booking_no_of_guests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
